### ISSUE TITLE
Feature request: add OAuth2 integrations (like Discord, etc...)

### ISSUE THREAD

**Issue by Bizzonium** [ss220-space/space-station-14#2]
Есть сетевые кодеры на шарпе? Надо в СС14 в офиц. репозиторий и в наш добавить систему привязки дискорда:

> 1. Игрок подключается
> 2. Игроку предлагается привязать дискорд
> 3. Игрок соглашается
> 4. У игрока открывается браузер с oauth2 авторизацией дискорда
> 5. Происходит редирект на REST API сервера сс14
> 6. Сервер получает информацию и записывает в БД (без дискорд токенов)

Добавить в сервер следующие конфиги:
> - discord.oauth_required = true
> - discord.oauth_clientid = ""
> - discord.oauth_secret = ""
> - discord.oauth_redirecturi = "" (тут будет ссылка на серверный обработчик)

Добавить в сервер следующие HTTP хендлеры:
- "/auth/callback/discord" (например)

Добавить таблицу, поля и миграции в Postgres БД для хранения информации о связанном дискорде
> "integrations" (например)
> - type_id
> - type_name - (тут могут быть discord, vk, reddit, twitter, forum, любой oauth2 источник)

> "connections" (например)
> - user_id (связанный ключ игрока)
> - intergation_type - integrations.type_id
> - connected_id - в данном случае тут будет discord_id

Надо ещё придумать как хранить дополнительную полученную информацию в универсальном виде независимо от типа интеграции. Для дискорда например:
> - username - the user's username, not unique across the platform
> - discriminator - the user's 4-digit discord-tag
> - mfa_enabled - whether the user has two factor enabled on their account
> - verified - whether the user has two factor enabled on their account
> - email
> - premium_type - the type of Nitro subscription on a user's account
> https://discord.com/developers/docs/resources/user

А ещё бы аппрувнуть идею у оффов

**Comment by enJey009** [comment]
Грубо говоря перенести систему привязки дискорда с сс13. А к чему будет привязка авторизации, по стиму? ну в BYOND там понять ckey есть и аккаунт сам, а тут непонятно. Да и вообще в этом репозитории что ты взял нету никакой авторизации или я чего-то не догоняю.

**Comment by Bizzonium** [comment]
Не совсем. В сс13 не такая система. Как я и написал, нужно привязать к аккаунту SS14 дискорд (или что-то ещё) игрока. Сюда просто надо добавить поддержку OAuth2 интеграций. Если когда-нибудь реализовывал такое в вебе, то сразу понятно в чём заключается цель и как это делается.

**Comment by enJey009** [comment]
Да я понимаю о чем идет речь, я не понимаю к какому аккаунту подвязывать надо? в версии стима там аккаунт стима, а у нас? там вроде просто строка ввода логина и всё или у нас будет отдельный лаунчер с регистрацией/авторизацией?
Или регистрация будет на сайте?

**Comment by Bizzonium** [comment]
> я не понимаю к какому аккаунту подвязывать надо? 

SS14, не стим https://central.spacestation14.io/web/
